"""Initial migration

Revision ID: 20323f22464e
Revises: 
Create Date: 2025-04-14 23:34:20.964520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20323f22464e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('barcode_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyers_barcode_id'), ['barcode_id'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('gregorian_date', sa.DateTime(), nullable=False),
    sa.Column('hebrew_date', sa.String(length=100), nullable=True),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('barcode_id', sa.String(length=50), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_barcode_id', ['barcode_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=True),
    sa.Column('manual_entry_notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_timestamp'))
        batch_op.drop_index(batch_op.f('ix_purchases_item_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_event_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_buyer_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_barcode_id')

    op.drop_table('items')
    op.drop_table('events')
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyers_barcode_id'))

    op.drop_table('buyers')
    # ### end Alembic commands ###
